const express=require("express")
const { AccountDeactivate, UpdateDeactivate,AccountDeactivateUpdateReason,GetAccountDeactivateUpdateReason } = require("../controllers/AccountDeactivate")
const AccountDeactivateRouter=express.Router()
const authMiddleware = require("../Middleware/Authmiddleware")
const { apiLimiter } = require("../Middleware/ReateLimeter")
AccountDeactivateRouter.post("/Deactivate",apiLimiter,AccountDeactivate)
AccountDeactivateRouter.post("/UpdateReason",authMiddleware,apiLimiter,AccountDeactivateUpdateReason)
AccountDeactivateRouter.get("/GetAllUpdateReason",apiLimiter,GetAccountDeactivateUpdateReason)
AccountDeactivateRouter.put("/UpdateDeactivate",apiLimiter,UpdateDeactivate)
module.exports=AccountDeactivateRouter